/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ForLabsRouteImport } from './routes/for-labs'
import { Route as ForPracticesRouteImport } from './routes/for-practices'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as IntegrationsRouteImport } from './routes/integrations'
import { Route as PlatformRouteImport } from './routes/platform'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ForLabsRoute = ForLabsRouteImport.update({
  id: '/for-labs',
  path: '/for-labs',
  getParentRoute: () => rootRouteImport,
} as any)
const ForPracticesRoute = ForPracticesRouteImport.update({
  id: '/for-practices',
  path: '/for-practices',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsRoute = IntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformRoute = PlatformRouteImport.update({
  id: '/platform',
  path: '/platform',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/for-labs': typeof ForLabsRoute
  '/for-practices': typeof ForPracticesRoute
  '/how-it-works': typeof HowItWorksRoute
  '/integrations': typeof IntegrationsRoute
  '/platform': typeof PlatformRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/for-labs': typeof ForLabsRoute
  '/for-practices': typeof ForPracticesRoute
  '/how-it-works': typeof HowItWorksRoute
  '/integrations': typeof IntegrationsRoute
  '/platform': typeof PlatformRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/for-labs': typeof ForLabsRoute
  '/for-practices': typeof ForPracticesRoute
  '/how-it-works': typeof HowItWorksRoute
  '/integrations': typeof IntegrationsRoute
  '/platform': typeof PlatformRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/for-labs'
    | '/for-practices'
    | '/how-it-works'
    | '/integrations'
    | '/platform'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/for-labs'
    | '/for-practices'
    | '/how-it-works'
    | '/integrations'
    | '/platform'
  id:
    | '__root__'
    | '/'
    | '/for-labs'
    | '/for-practices'
    | '/how-it-works'
    | '/integrations'
    | '/platform'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ForLabsRoute: typeof ForLabsRoute
  ForPracticesRoute: typeof ForPracticesRoute
  HowItWorksRoute: typeof HowItWorksRoute
  IntegrationsRoute: typeof IntegrationsRoute
  PlatformRoute: typeof PlatformRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-labs': {
      id: '/for-labs'
      path: '/for-labs'
      fullPath: '/for-labs'
      preLoaderRoute: typeof ForLabsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-practices': {
      id: '/for-practices'
      path: '/for-practices'
      fullPath: '/for-practices'
      preLoaderRoute: typeof ForPracticesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations': {
      id: '/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof IntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform': {
      id: '/platform'
      path: '/platform'
      fullPath: '/platform'
      preLoaderRoute: typeof PlatformRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ForLabsRoute: ForLabsRoute,
  ForPracticesRoute: ForPracticesRoute,
  HowItWorksRoute: HowItWorksRoute,
  IntegrationsRoute: IntegrationsRoute,
  PlatformRoute: PlatformRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
