import {
  COLOR,
  COAT,
  DEMO_ORG_ID,
  DEMO_USER_ID,
  LAB,
  LD,
  LOC_MAIN,
  LOC_NORTH,
  MAT,
  MFR,
  MIRROR,
  PHOTO,
  POL,
  PROD,
  SEED_TS,
  TINT,
  VT,
} from "./ids";
import type {
  Coating,
  Lab,
  LabLensOffering,
  LensConfigDatabase,
  LensDesign,
  LensMaterial,
  LensProduct,
  Manufacturer,
  MirrorOption,
  PhotochromicColor,
  PhotochromicProduct,
  PolarizationOption,
  RoutingRule,
  TintOption,
  VisionType,
} from "./types";

const stamp = { createdAt: SEED_TS, updatedAt: SEED_TS };

function vision(
  id: string,
  code: string,
  name: string,
  description: string,
  sortOrder: number,
): VisionType {
  return { id, code, name, description, active: true, sortOrder };
}

function design(
  id: string,
  visionTypeId: string,
  code: string,
  name: string,
  flags: {
    add?: boolean;
    seg?: boolean;
    fit?: boolean;
    pow?: boolean;
    minFit?: number | null;
  },
  sortOrder: number,
): LensDesign {
  return {
    id,
    visionTypeId,
    code,
    name,
    description: name,
    requiresAddPower: flags.add === true,
    requiresSegmentHeight: flags.seg === true,
    requiresFittingHeight: flags.fit === true,
    requiresPositionOfWear: flags.pow === true,
    minimumFittingHeight: flags.minFit ?? null,
    active: true,
    sortOrder,
  };
}

function material(
  id: string,
  code: string,
  name: string,
  refractiveIndex: number,
  impactResistant: boolean,
  sortOrder: number,
  abbeValue: number | null = null,
): LensMaterial {
  return {
    id,
    code,
    name,
    refractiveIndex,
    abbeValue,
    specificGravity: null,
    impactResistant,
    active: true,
    sortOrder,
  };
}

export function emptyDatabase(): LensConfigDatabase {
  return {
    manufacturers: [],
    visionTypes: [],
    lensDesigns: [],
    materials: [],
    products: [],
    productMaterials: [],
    coatings: [],
    photochromicProducts: [],
    photochromicColors: [],
    photochromicProductColors: [],
    polarizationOptions: [],
    tintOptions: [],
    mirrorOptions: [],
    labs: [],
    locations: [],
    offerings: [],
    routingRules: [],
    orders: [],
    auditLog: [],
  };
}

export function seedReferenceData(): Pick<
  LensConfigDatabase,
  | "manufacturers"
  | "visionTypes"
  | "lensDesigns"
  | "materials"
  | "coatings"
  | "photochromicProducts"
  | "photochromicColors"
  | "photochromicProductColors"
  | "polarizationOptions"
  | "tintOptions"
  | "mirrorOptions"
> {
  const manufacturers: Manufacturer[] = (
    [
      ["ESSILOR", "Essilor"],
      ["HOYA", "HOYA"],
      ["ZEISS", "ZEISS"],
      ["SHAMIR", "Shamir"],
      ["IOT", "IOT"],
      ["YOUNGER", "Younger Optics"],
      ["KODAK", "Kodak"],
      ["SEIKO", "Seiko"],
      ["HOUSE", "Lab House Brand"],
      ["OTHER", "Other"],
      ["TRANSITIONS", "Transitions"],
    ] as const
  ).map(([code, name]) => ({
    id: `mfr_${code}`,
    name,
    active: true,
    organizationId: null,
    ...stamp,
  }));

  const visionTypes: VisionType[] = [
    vision(VT.sv, "SINGLE_VISION", "Single Vision", "Single-vision distance or near.", 10),
    vision(VT.dsv, "DIGITAL_SINGLE_VISION", "Digital Single Vision", "Digitally surfaced SV.", 20),
    vision(VT.af, "ANTI_FATIGUE", "Anti-Fatigue", "Boost near for digital strain.", 30),
    vision(VT.bf, "BIFOCAL", "Bifocal", "Lined two-zone lens.", 40),
    vision(VT.bbf, "BLENDED_BIFOCAL", "Blended Bifocal", "No-line blended bifocal.", 50),
    vision(VT.tf, "TRIFOCAL", "Trifocal", "Lined three-zone lens.", 60),
    vision(VT.pg, "PROGRESSIVE", "Progressive", "No-line multifocal.", 70),
    vision(VT.occ, "OCCUPATIONAL", "Occupational", "Task-specific near/intermediate.", 80),
    vision(VT.computer, "COMPUTER", "Computer", "Intermediate-dominant computer lens.", 90),
    vision(VT.myopia, "MYOPIA_CONTROL", "Myopia Control", "Spectacle myopia-control designs.", 100),
    vision(VT.spec, "SPECIALTY", "Specialty", "Specialty and industrial designs.", 110),
  ];

  const sv = { add: false, seg: false, fit: false, pow: false };
  const dsv = { add: false, seg: false, fit: true, pow: true, minFit: 14 };
  const af = { add: true, seg: false, fit: true, pow: false, minFit: 14 };
  const lined = { add: true, seg: true, fit: false, pow: false };
  const pg = { add: true, seg: false, fit: true, pow: true, minFit: 14 };
  const occ = { add: true, seg: false, fit: true, pow: true, minFit: 16 };

  const lensDesigns: LensDesign[] = [
    design(LD.convSv, VT.sv, "CONVENTIONAL_SV", "Conventional Single Vision", sv, 10),
    design(LD.asphericSv, VT.sv, "ASPHERIC_SV", "Aspheric Single Vision", sv, 20),
    design(LD.digitalSv, VT.dsv, "DIGITAL_SV", "Digital Single Vision", dsv, 30),
    design(
      LD.personalSv,
      VT.dsv,
      "PERSONALIZED_DSV",
      "Personalized Digital Single Vision",
      dsv,
      40,
    ),
    design(LD.lowBoost, VT.af, "LOW_BOOST", "Low Boost", af, 10),
    design(LD.medBoost, VT.af, "MED_BOOST", "Medium Boost", af, 20),
    design(LD.highBoost, VT.af, "HIGH_BOOST", "High Boost", af, 30),
    design(LD.ft28, VT.bf, "FT28", "Flat Top 28", lined, 10),
    design(LD.ft35, VT.bf, "FT35", "Flat Top 35", lined, 20),
    design(LD.ft45, VT.bf, "FT45", "Flat Top 45", lined, 30),
    design(LD.execBf, VT.bf, "EXEC_BF", "Executive Bifocal", lined, 40),
    design(LD.roundSeg, VT.bf, "ROUND_SEG", "Round Segment", lined, 50),
    design(LD.blendedRound, VT.bbf, "BLENDED_ROUND", "Blended Round Segment", lined, 10),
    design(LD.ft7x28, VT.tf, "FT_7X28", "Flat Top 7x28", lined, 10),
    design(LD.ft8x35, VT.tf, "FT_8X35", "Flat Top 8x35", lined, 20),
    design(LD.execTf, VT.tf, "EXEC_TF", "Executive Trifocal", lined, 30),
    design(LD.stdPg, VT.pg, "STD_PG", "Standard Progressive", pg, 10),
    design(LD.ffPg, VT.pg, "FF_PG", "Digital Free-Form Progressive", pg, 20),
    design(
      LD.personalPg,
      VT.pg,
      "PERSONAL_PG",
      "Personalized Progressive",
      { ...pg, minFit: 16 },
      30,
    ),
    design(LD.shortPg, VT.pg, "SHORT_PG", "Short-Corridor Progressive", { ...pg, minFit: 13 }, 40),
    design(LD.softPg, VT.pg, "SOFT_PG", "Soft-Design Progressive", pg, 50),
    design(LD.hardPg, VT.pg, "HARD_PG", "Hard-Design Progressive", pg, 60),
    design(LD.distPg, VT.pg, "DIST_PG", "Distance-Dominant Progressive", pg, 70),
    design(LD.nearPg, VT.pg, "NEAR_PG", "Near-Dominant Progressive", pg, 80),
    design(LD.wrapPg, VT.pg, "WRAP_PG", "Wrap Progressive", pg, 90),
    design(LD.officePg, VT.occ, "OFFICE_PG", "Office Progressive", occ, 10),
    design(LD.computerPg, VT.computer, "COMPUTER_PG", "Computer Progressive", occ, 10),
    design(LD.enhancedNear, VT.occ, "ENHANCED_NEAR", "Enhanced Near", occ, 20),
    design(LD.doubleD, VT.occ, "DOUBLE_D", "Double-D Progressive", { ...occ, seg: true }, 30),
    design(LD.occBf, VT.occ, "OCC_BF", "Occupational Bifocal", lined, 40),
    design(LD.defocus, VT.myopia, "DEFOCUS_MC", "Defocus-Based Myopia-Control Lens", sv, 10),
    design(LD.lenslet, VT.myopia, "LENSLET_MC", "Lenslet-Based Myopia-Control Lens", sv, 20),
    design(LD.otherMc, VT.myopia, "OTHER_MC", "Other Myopia-Control Spectacle Lens", sv, 30),
    design(LD.doubleSeg, VT.spec, "DOUBLE_SEG", "Double Segment", lined, 10),
    design(LD.franklin, VT.spec, "FRANKLIN", "Franklin Split", lined, 20),
    design(LD.lenticular, VT.spec, "LENTICULAR", "Lenticular", sv, 30),
    design(LD.slabOff, VT.spec, "SLAB_OFF", "Slab-Off", { add: true }, 40),
    design(LD.reverseSlab, VT.spec, "REV_SLAB", "Reverse Slab-Off", { add: true }, 50),
    design(LD.safety, VT.spec, "SAFETY", "Safety/Industrial", sv, 60),
    design(LD.sports, VT.spec, "SPORTS", "Sports/Wrap", { pow: true }, 70),
  ];

  const materials: LensMaterial[] = [
    material(MAT.glass, "CROWN_GLASS", "Crown Glass", 1.523, false, 10, 59),
    material(MAT.hiGlass, "HI_GLASS", "High-Index Glass", 1.7, false, 20, 35),
    material(MAT.cr39, "CR39", "CR-39 / 1.50", 1.5, false, 30, 58),
    material(MAT.trivex, "TRIVEX", "1.53 Trivex", 1.53, true, 40, 44),
    material(MAT.mid156, "156", "1.56 Mid-Index", 1.56, false, 50, 37),
    material(MAT.poly, "POLY", "1.59 Polycarbonate", 1.59, true, 60, 30),
    material(MAT.hi160, "160", "1.60 High Index", 1.6, false, 70, 36),
    material(MAT.hi167, "167", "1.67 High Index", 1.67, false, 80, 32),
    material(MAT.hi170, "170", "1.70 High Index", 1.7, false, 90, 36),
    material(MAT.uhi174, "174", "1.74 Ultra High Index", 1.74, false, 100, 33),
    material(MAT.uhi176, "176", "1.76 Ultra High Index", 1.76, false, 110, 30),
    material(MAT.specialty, "SPECIALTY", "Proprietary/Specialty Material", 1.6, false, 120, null),
  ];

  const coatings: Coating[] = [
    coat(COAT.uncoated, "Uncoated", "UNCOATED", "UNCOATED", "NONE", false, false, false),
    coat(
      COAT.hard,
      "Scratch-Resistant Hard Coat",
      "HARD_COAT",
      "SCRATCH_RESISTANT",
      "NONE",
      true,
      false,
      false,
    ),
    coat(COAT.standardAr, "Standard AR", "STD_AR", "STANDARD_AR", "STANDARD", true, true, true),
    coat(COAT.premiumAr, "Premium AR", "PREMIUM_AR", "PREMIUM_AR", "PREMIUM", true, true, true),
    coat(
      COAT.ultraAr,
      "Ultra-Premium AR",
      "ULTRA_AR",
      "ULTRA_PREMIUM_AR",
      "ULTRA_PREMIUM",
      true,
      true,
      true,
    ),
    coat(
      COAT.blueAr,
      "Blue-Filtering AR",
      "BLUE_AR",
      "BLUE_FILTERING_AR",
      "PREMIUM",
      true,
      true,
      true,
      "CLEAR_FILTER",
    ),
    {
      ...coat(
        COAT.backsideAr,
        "Backside AR",
        "BACK_AR",
        "STANDARD_AR",
        "STANDARD",
        true,
        false,
        true,
      ),
    },
    {
      ...coat(
        COAT.antiFog,
        "Anti-Fog Coating",
        "ANTI_FOG",
        "SPECIALTY",
        "NONE",
        true,
        false,
        false,
      ),
      antiFog: true,
    },
    coat(COAT.specialty, "Specialty Coating", "SPECIALTY", "SPECIALTY", "NONE", true, false, false),
  ];

  const photochromicProducts: PhotochromicProduct[] = [
    photo(PHOTO.genS, "Transitions GEN S", "TRANSITIONS_GEN_S", "STANDARD", false, false, false),
    photo(
      PHOTO.xtractive,
      "Transitions XTRActive",
      "TRANSITIONS_XTRACTIVE",
      "EXTRA_DARK",
      true,
      false,
      false,
    ),
    photo(
      PHOTO.xtractivePol,
      "Transitions XTRActive Polarized",
      "TRANSITIONS_XTRACTIVE_POL",
      "PHOTOCHROMIC_POLARIZED",
      true,
      true,
      false,
    ),
    photo(
      PHOTO.drivewear,
      "Transitions Drivewear",
      "TRANSITIONS_DRIVEWEAR",
      "IN_CAR",
      true,
      true,
      false,
    ),
    photo(
      PHOTO.style,
      "Transitions Style Colors",
      "TRANSITIONS_STYLE",
      "STANDARD",
      false,
      false,
      false,
    ),
    photo(PHOTO.sensity, "Sensity", "SENSITY", "STANDARD", false, false, false),
    photo(PHOTO.sensityDark, "Sensity Dark", "SENSITY_DARK", "EXTRA_DARK", true, false, false),
    photo(PHOTO.sensityFast, "Sensity Fast", "SENSITY_FAST", "STANDARD", false, false, false),
    photo(PHOTO.photofusion, "PhotoFusion X", "PHOTOFUSION_X", "STANDARD", false, false, false),
    photo(PHOTO.colormatic, "ColorMatic", "COLORMATIC", "STANDARD", false, false, false),
    photo(PHOTO.liferx, "LifeRx", "LIFERX", "STANDARD", false, false, false),
    photo(PHOTO.house, "Lab House Photochromic", "HOUSE_PHOTO", "HOUSE_BRAND", false, false, false),
    photo(PHOTO.other, "Other", "OTHER_PHOTO", "OTHER", false, false, false),
  ];

  const photochromicColors: PhotochromicColor[] = (
    [
      ["GRAY", "Gray", "#6b6f76"],
      ["BROWN", "Brown", "#6b4a32"],
      ["GRAPHITE_GREEN", "Graphite Green", "#3f4f45"],
      ["EMERALD", "Emerald", "#2e6b4f"],
      ["SAPPHIRE", "Sapphire", "#2f5d8c"],
      ["AMETHYST", "Amethyst", "#6a4c8a"],
      ["AMBER", "Amber", "#c47b2d"],
      ["RUBY", "Ruby", "#8b2e3a"],
      ["GRAY_GREEN", "Gray-Green", "#5a6a5e"],
      ["COPPER", "Copper", "#b46a3c"],
      ["BLUE", "Blue", "#3a6ea8"],
      ["VIOLET", "Violet", "#6b4ea2"],
      ["ROSE", "Rose", "#c47a8a"],
      ["OTHER", "Other", null],
    ] as const
  ).map(([code, name, hex], i) => ({
    id: `pcol_${code}`,
    name,
    code,
    hexColor: hex,
    active: true,
    sortOrder: (i + 1) * 10,
  }));

  const genSColors = [
    COLOR.gray,
    COLOR.brown,
    COLOR.graphiteGreen,
    COLOR.emerald,
    COLOR.sapphire,
    COLOR.amethyst,
    COLOR.amber,
    COLOR.ruby,
  ];
  const xtractiveColors = [COLOR.gray, COLOR.brown, COLOR.graphiteGreen];
  const styleColors = [COLOR.emerald, COLOR.sapphire, COLOR.amethyst, COLOR.amber, COLOR.ruby];
  const genericColors = [COLOR.gray, COLOR.brown];

  const photochromicProductColors = [
    ...linkColors(PHOTO.genS, genSColors),
    ...linkColors(PHOTO.xtractive, xtractiveColors),
    ...linkColors(PHOTO.xtractivePol, [COLOR.gray, COLOR.brown]),
    ...linkColors(PHOTO.drivewear, [COLOR.brown, COLOR.copper]),
    ...linkColors(PHOTO.style, styleColors),
    ...linkColors(PHOTO.sensity, genericColors),
    ...linkColors(PHOTO.sensityDark, genericColors),
    ...linkColors(PHOTO.sensityFast, genericColors),
    ...linkColors(PHOTO.photofusion, genericColors),
    ...linkColors(PHOTO.colormatic, genericColors),
    ...linkColors(PHOTO.liferx, genericColors),
    ...linkColors(PHOTO.house, genericColors),
    ...linkColors(PHOTO.other, [COLOR.other]),
  ];

  const polarizationOptions: PolarizationOption[] = (
    [
      ["NONE", "None", "None"],
      ["GRAY", "Gray Polarized", "Gray"],
      ["BROWN", "Brown Polarized", "Brown"],
      ["GREEN", "Green Polarized", "Green"],
      ["COPPER", "Copper Polarized", "Copper"],
      ["BLUE", "Blue Polarized", "Blue"],
      ["ROSE", "Rose Polarized", "Rose"],
      ["YELLOW", "Yellow Polarized", "Yellow"],
      ["OTHER", "Other Polarized", "Other"],
    ] as const
  ).map(([code, name, color]) => ({
    id: `pol_${code}`,
    name,
    code,
    color,
    active: true,
  }));

  const tintOptions: TintOption[] = [
    {
      id: TINT.none,
      organizationId: null,
      name: "None",
      code: "NONE",
      tintType: "NONE",
      color: "None",
      defaultDensityPercent: null,
      transmissionPercent: null,
      therapeuticFilter: false,
      active: true,
    },
    {
      id: TINT.solidGray,
      organizationId: null,
      name: "Solid Gray",
      code: "SOLID_GRAY",
      tintType: "SOLID",
      color: "Gray",
      defaultDensityPercent: 80,
      transmissionPercent: 15,
      therapeuticFilter: false,
      active: true,
    },
    {
      id: TINT.fl41,
      organizationId: null,
      name: "FL-41 Medical Filter",
      code: "FL41",
      tintType: "FL_41",
      color: "Rose",
      defaultDensityPercent: 50,
      transmissionPercent: 50,
      therapeuticFilter: true,
      active: true,
    },
  ];

  const mirrorOptions: MirrorOption[] = (
    [
      ["NONE", "None", "NONE", "None"],
      ["SILVER", "Silver", "SOLID", "Silver"],
      ["GOLD", "Gold", "FLASH", "Gold"],
      ["BLUE", "Blue", "FLASH", "Blue"],
      ["GREEN", "Green", "FLASH", "Green"],
      ["RED", "Red", "FLASH", "Red"],
      ["ORANGE", "Orange", "FLASH", "Orange"],
      ["ROSE", "Rose", "FLASH", "Rose"],
      ["PURPLE", "Purple", "FLASH", "Purple"],
      ["BLACK", "Black", "SOLID", "Black"],
      ["CUSTOM", "Custom", "SOLID", "Custom"],
    ] as const
  ).map(([code, name, type, color]) => ({
    id: `mirror_${code}`,
    organizationId: null,
    name,
    code,
    mirrorType: type,
    color,
    active: true,
  }));

  return {
    manufacturers,
    visionTypes,
    lensDesigns,
    materials,
    coatings,
    photochromicProducts,
    photochromicColors,
    photochromicProductColors,
    polarizationOptions,
    tintOptions,
    mirrorOptions,
  };
}

function coat(
  id: string,
  name: string,
  code: string,
  coatingTier: Coating["coatingTier"],
  arLevel: Coating["arLevel"],
  hardCoat: boolean,
  front: boolean,
  back: boolean,
  blue: Coating["blueLightFilterType"] = "NONE",
): Coating {
  return {
    id,
    organizationId: null,
    manufacturerId: null,
    name,
    code,
    coatingTier,
    hardCoat,
    arLevel,
    frontSurfaceAr: front,
    backSurfaceAr: back,
    blueLightFilterType: blue,
    uvProtection: true,
    hydrophobic: arLevel !== "NONE",
    oleophobic: arLevel === "PREMIUM" || arLevel === "ULTRA_PREMIUM",
    antiStatic: arLevel === "ULTRA_PREMIUM",
    antiSmudge: arLevel !== "NONE",
    dustResistant: arLevel === "ULTRA_PREMIUM",
    antiFog: false,
    reflectionColor: null,
    warrantyMonths: arLevel === "ULTRA_PREMIUM" ? 24 : arLevel === "PREMIUM" ? 12 : null,
    description: name,
    active: true,
    createdBy: null,
    ...stamp,
  };
}

function photo(
  id: string,
  name: string,
  code: string,
  photochromicType: PhotochromicProduct["photochromicType"],
  windshield: boolean,
  polarizedWhenActivated: boolean,
  permanentlyPolarized: boolean,
): PhotochromicProduct {
  return {
    id,
    organizationId: null,
    manufacturerId: MFR.transitions,
    name,
    code,
    photochromicType,
    activatesBehindWindshield: windshield,
    polarizedWhenActivated,
    permanentlyPolarized,
    blueLightFiltering: true,
    indoorStateDescription: "Near-clear indoors",
    outdoorStateDescription: "Darkens outdoors",
    active: true,
    createdBy: null,
    ...stamp,
  };
}

function linkColors(productId: string, colorIds: string[]) {
  return colorIds.map((colorId) => ({
    id: `ppc_${productId}_${colorId}`,
    photochromicProductId: productId,
    photochromicColorId: colorId,
    active: true,
  }));
}

function offering(
  partial: Omit<
    LabLensOffering,
    | "createdAt"
    | "updatedAt"
    | "createdBy"
    | "labCoatingCode"
    | "labPhotochromicCode"
    | "labMaterialCode"
  > &
    Partial<
      Pick<
        LabLensOffering,
        | "createdAt"
        | "updatedAt"
        | "createdBy"
        | "labCoatingCode"
        | "labPhotochromicCode"
        | "labMaterialCode"
      >
    >,
): LabLensOffering {
  return {
    createdBy: DEMO_USER_ID,
    labCoatingCode: null,
    labPhotochromicCode: null,
    labMaterialCode: null,
    ...stamp,
    ...partial,
  };
}

export function seedDemoDatabase(organizationId = DEMO_ORG_ID): LensConfigDatabase {
  const reference = seedReferenceData();
  const products: LensProduct[] = [
    {
      id: PROD.svClear,
      organizationId,
      manufacturerId: MFR.essilor,
      visionTypeId: VT.sv,
      lensDesignId: LD.convSv,
      productName: "Essilor Single Vision",
      productCode: "ESV",
      description: "Clear conventional single vision.",
      active: true,
      positionOfWearSupported: false,
      notes: "",
      createdBy: DEMO_USER_ID,
      ...stamp,
    },
    {
      id: PROD.pgClear,
      organizationId,
      manufacturerId: MFR.essilor,
      visionTypeId: VT.pg,
      lensDesignId: LD.ffPg,
      productName: "Varilux Comfort Max",
      productCode: "VCM",
      description: "Digital free-form progressive.",
      active: true,
      positionOfWearSupported: true,
      notes: "",
      createdBy: DEMO_USER_ID,
      ...stamp,
    },
    {
      id: PROD.svSun,
      organizationId,
      manufacturerId: MFR.younger,
      visionTypeId: VT.sv,
      lensDesignId: LD.asphericSv,
      productName: "NuPolar Single Vision",
      productCode: "NPSV",
      description: "Polarized sun single vision.",
      active: true,
      positionOfWearSupported: false,
      notes: "",
      createdBy: DEMO_USER_ID,
      ...stamp,
    },
    {
      id: PROD.pgSun,
      organizationId,
      manufacturerId: MFR.essilor,
      visionTypeId: VT.pg,
      lensDesignId: LD.ffPg,
      productName: "Varilux Sun Progressive",
      productCode: "VSP",
      description: "Progressive sun / polarized.",
      active: true,
      positionOfWearSupported: true,
      notes: "",
      createdBy: DEMO_USER_ID,
      ...stamp,
    },
  ];

  const productMaterials = [
    { id: "pm_sv_poly", lensProductId: PROD.svClear, lensMaterialId: MAT.poly, active: true },
    { id: "pm_sv_167", lensProductId: PROD.svClear, lensMaterialId: MAT.hi167, active: true },
    { id: "pm_sv_cr39", lensProductId: PROD.svClear, lensMaterialId: MAT.cr39, active: true },
    { id: "pm_sv_trivex", lensProductId: PROD.svClear, lensMaterialId: MAT.trivex, active: true },
    { id: "pm_pg_poly", lensProductId: PROD.pgClear, lensMaterialId: MAT.poly, active: true },
    { id: "pm_pg_167", lensProductId: PROD.pgClear, lensMaterialId: MAT.hi167, active: true },
    { id: "pm_svsun_poly", lensProductId: PROD.svSun, lensMaterialId: MAT.poly, active: true },
    { id: "pm_pgsun_167", lensProductId: PROD.pgSun, lensMaterialId: MAT.hi167, active: true },
    { id: "pm_pgsun_poly", lensProductId: PROD.pgSun, lensMaterialId: MAT.poly, active: true },
  ];

  const labs: Lab[] = [
    {
      id: LAB.midwest,
      organizationId,
      name: "Midwest Optical Lab",
      accountNumber: "MW-1001",
      contactName: "Alex Rivera",
      phone: "555-0101",
      email: "orders@midwest.example",
      orderingMethod: "API",
      active: true,
      notes: "Primary lab.",
      createdBy: DEMO_USER_ID,
      ...stamp,
    },
    {
      id: LAB.coastal,
      organizationId,
      name: "Coastal Rx Lab",
      accountNumber: "CO-2002",
      contactName: "Jordan Lee",
      phone: "555-0202",
      email: "lab@coastal.example",
      orderingMethod: "PORTAL",
      active: true,
      notes: "Backup lab with wider Rx range.",
      createdBy: DEMO_USER_ID,
      ...stamp,
    },
    {
      id: LAB.specialty,
      organizationId,
      name: "Summit Specialty Lab",
      accountNumber: "SS-3003",
      contactName: "Sam Patel",
      phone: "555-0303",
      email: "specialty@summit.example",
      orderingMethod: "EMAIL",
      active: true,
      notes: "Sun, medical filters, and specialty.",
      createdBy: DEMO_USER_ID,
      ...stamp,
    },
  ];

  const baseLimits = {
    sphereMin: -8,
    sphereMax: 8,
    cylinderMin: -4,
    cylinderMax: 0,
    addMin: 0.75,
    addMax: 3.5,
    prismHorizontalMax: 4,
    prismVerticalMax: 3,
    totalPrismMax: 5,
    minimumFittingHeight: 14,
    minimumBlankSize: 60,
    maximumBlankSize: 80,
    minimumCenterThickness: 1.0,
    maximumDecentration: 10,
    drillMountAllowed: true,
    grooveAllowed: true,
    rimlessAllowed: true,
    wrapAllowed: false,
    safetyFrameAllowed: true,
    edgePolishAvailable: true,
    rollAndPolishAvailable: true,
    specialBaseCurveRequired: false,
    supportedBaseCurves: "4,6,8",
    restrictionsJson: null,
    rushAvailable: true,
    rushCost: 25,
    warrantyMonths: 12,
    remakePolicy: "First remake no charge within 12 months.",
    notes: "",
    locationId: null,
    effectiveStartDate: "2026-01-01",
    effectiveEndDate: null,
    retailPrice: null,
  };

  const offerings: LabLensOffering[] = [
    offering({
      id: "off_sv_poly_ar_mw",
      organizationId,
      labId: LAB.midwest,
      lensProductId: PROD.svClear,
      lensMaterialId: MAT.poly,
      coatingId: COAT.premiumAr,
      photochromicProductId: null,
      photochromicColorId: null,
      polarizationOptionId: POL.none,
      tintOptionId: TINT.none,
      mirrorOptionId: MIRROR.none,
      labProductName: "MW SV Poly Premium AR",
      labProductCode: "MW-SV-POLY-PAR",
      cost: 28,
      estimatedTurnaroundBusinessDays: 3,
      active: true,
      ...baseLimits,
      sphereMin: -2,
      sphereMax: 2,
    }),
    offering({
      id: "off_sv_poly_ar_co",
      organizationId,
      labId: LAB.coastal,
      lensProductId: PROD.svClear,
      lensMaterialId: MAT.poly,
      coatingId: COAT.premiumAr,
      photochromicProductId: null,
      photochromicColorId: null,
      polarizationOptionId: POL.none,
      tintOptionId: TINT.none,
      mirrorOptionId: MIRROR.none,
      labProductName: "Coastal SV Poly Premium AR",
      labProductCode: "CO-SV-POLY-PAR",
      cost: 32,
      estimatedTurnaroundBusinessDays: 4,
      active: true,
      ...baseLimits,
    }),
    offering({
      id: "off_pg_167_ultra_mw",
      organizationId,
      labId: LAB.midwest,
      lensProductId: PROD.pgClear,
      lensMaterialId: MAT.hi167,
      coatingId: COAT.ultraAr,
      photochromicProductId: null,
      photochromicColorId: null,
      polarizationOptionId: POL.none,
      tintOptionId: TINT.none,
      mirrorOptionId: MIRROR.none,
      labProductName: "MW Varilux 1.67 Ultra AR",
      labProductCode: "MW-PG-167-UAR",
      cost: 96,
      estimatedTurnaroundBusinessDays: 5,
      active: true,
      ...baseLimits,
    }),
    offering({
      id: "off_sv_poly_gens_mw",
      organizationId,
      labId: LAB.midwest,
      lensProductId: PROD.svClear,
      lensMaterialId: MAT.poly,
      coatingId: COAT.premiumAr,
      photochromicProductId: PHOTO.genS,
      photochromicColorId: COLOR.gray,
      polarizationOptionId: POL.none,
      tintOptionId: TINT.none,
      mirrorOptionId: MIRROR.none,
      labProductName: "MW SV Poly GEN S Gray",
      labProductCode: "MW-SV-GENS-GY",
      labPhotochromicCode: "GENS-GY",
      cost: 58,
      estimatedTurnaroundBusinessDays: 4,
      active: true,
      ...baseLimits,
    }),
    offering({
      id: "off_pg_167_xtr_br_mw",
      organizationId,
      labId: LAB.midwest,
      lensProductId: PROD.pgClear,
      lensMaterialId: MAT.hi167,
      coatingId: COAT.premiumAr,
      photochromicProductId: PHOTO.xtractive,
      photochromicColorId: COLOR.brown,
      polarizationOptionId: POL.none,
      tintOptionId: TINT.none,
      mirrorOptionId: MIRROR.none,
      labProductName: "MW PG 1.67 XTRActive Brown",
      labProductCode: "MW-PG-XTR-BR",
      cost: 118,
      estimatedTurnaroundBusinessDays: 6,
      active: true,
      ...baseLimits,
    }),
    offering({
      id: "off_sv_poly_pol_ss",
      organizationId,
      labId: LAB.specialty,
      lensProductId: PROD.svSun,
      lensMaterialId: MAT.poly,
      coatingId: COAT.backsideAr,
      photochromicProductId: null,
      photochromicColorId: null,
      polarizationOptionId: POL.gray,
      tintOptionId: TINT.none,
      mirrorOptionId: MIRROR.none,
      labProductName: "Summit SV Polar Gray Back AR",
      labProductCode: "SS-SV-POL-GY",
      cost: 44,
      estimatedTurnaroundBusinessDays: 5,
      active: true,
      ...baseLimits,
      wrapAllowed: true,
    }),
    offering({
      id: "off_pg_pol_br_ss",
      organizationId,
      labId: LAB.specialty,
      lensProductId: PROD.pgSun,
      lensMaterialId: MAT.hi167,
      coatingId: COAT.premiumAr,
      photochromicProductId: null,
      photochromicColorId: null,
      polarizationOptionId: POL.brown,
      tintOptionId: TINT.none,
      mirrorOptionId: MIRROR.none,
      labProductName: "Summit PG Polar Brown",
      labProductCode: "SS-PG-POL-BR",
      cost: 132,
      estimatedTurnaroundBusinessDays: 7,
      active: true,
      ...baseLimits,
    }),
    offering({
      id: "off_sv_xtrpol_mw",
      organizationId,
      labId: LAB.midwest,
      lensProductId: PROD.svClear,
      lensMaterialId: MAT.poly,
      coatingId: COAT.premiumAr,
      photochromicProductId: PHOTO.xtractivePol,
      photochromicColorId: COLOR.gray,
      polarizationOptionId: POL.none,
      tintOptionId: TINT.none,
      mirrorOptionId: MIRROR.none,
      labProductName: "MW SV XTRActive Polarized Gray",
      labProductCode: "MW-SV-XTRPOL",
      cost: 78,
      estimatedTurnaroundBusinessDays: 5,
      active: true,
      ...baseLimits,
    }),
    offering({
      id: "off_sv_fl41_ss",
      organizationId,
      labId: LAB.specialty,
      lensProductId: PROD.svClear,
      lensMaterialId: MAT.poly,
      coatingId: COAT.hard,
      photochromicProductId: null,
      photochromicColorId: null,
      polarizationOptionId: POL.none,
      tintOptionId: TINT.fl41,
      mirrorOptionId: MIRROR.none,
      labProductName: "Summit SV FL-41",
      labProductCode: "SS-SV-FL41",
      cost: 39,
      estimatedTurnaroundBusinessDays: 6,
      active: true,
      ...baseLimits,
    }),
    offering({
      id: "off_sv_mirror_ss",
      organizationId,
      labId: LAB.specialty,
      lensProductId: PROD.svSun,
      lensMaterialId: MAT.poly,
      coatingId: COAT.backsideAr,
      photochromicProductId: null,
      photochromicColorId: null,
      polarizationOptionId: POL.gray,
      tintOptionId: TINT.none,
      mirrorOptionId: MIRROR.blue,
      labProductName: "Summit SV Polar Gray Blue Mirror",
      labProductCode: "SS-SV-MIR-BL",
      cost: 62,
      estimatedTurnaroundBusinessDays: 7,
      active: true,
      ...baseLimits,
      wrapAllowed: true,
    }),
    offering({
      id: "off_sv_poly_ar_mw_expired",
      organizationId,
      labId: LAB.midwest,
      lensProductId: PROD.svClear,
      lensMaterialId: MAT.cr39,
      coatingId: COAT.premiumAr,
      photochromicProductId: null,
      photochromicColorId: null,
      polarizationOptionId: POL.none,
      tintOptionId: TINT.none,
      mirrorOptionId: MIRROR.none,
      labProductName: "Expired CR-39 offering",
      labProductCode: "MW-EXPIRED",
      cost: 18,
      estimatedTurnaroundBusinessDays: 3,
      active: true,
      ...baseLimits,
      effectiveStartDate: "2024-01-01",
      effectiveEndDate: "2025-12-31",
    }),
    offering({
      id: "off_sv_poly_ar_mw_inactive",
      organizationId,
      labId: LAB.midwest,
      lensProductId: PROD.svClear,
      lensMaterialId: MAT.trivex,
      coatingId: COAT.premiumAr,
      photochromicProductId: null,
      photochromicColorId: null,
      polarizationOptionId: POL.none,
      tintOptionId: TINT.none,
      mirrorOptionId: MIRROR.none,
      labProductName: "Inactive Trivex offering",
      labProductCode: "MW-INACTIVE",
      cost: 34,
      estimatedTurnaroundBusinessDays: 3,
      active: false,
      ...baseLimits,
    }),
  ];

  const routingRules: RoutingRule[] = [
    rule(
      organizationId,
      "rr_sv_poly_ar_1",
      "SV Poly Premium AR — preferred",
      PROD.svClear,
      MAT.poly,
      COAT.premiumAr,
      null,
      null,
      POL.none,
      TINT.none,
      MIRROR.none,
      1,
      "off_sv_poly_ar_mw",
    ),
    rule(
      organizationId,
      "rr_sv_poly_ar_2",
      "SV Poly Premium AR — backup",
      PROD.svClear,
      MAT.poly,
      COAT.premiumAr,
      null,
      null,
      POL.none,
      TINT.none,
      MIRROR.none,
      2,
      "off_sv_poly_ar_co",
    ),
    rule(
      organizationId,
      "rr_pg_167_1",
      "PG 1.67 Ultra AR — preferred",
      PROD.pgClear,
      MAT.hi167,
      COAT.ultraAr,
      null,
      null,
      POL.none,
      TINT.none,
      MIRROR.none,
      1,
      "off_pg_167_ultra_mw",
    ),
    rule(
      organizationId,
      "rr_sv_gens_1",
      "SV GEN S Gray — preferred",
      PROD.svClear,
      MAT.poly,
      COAT.premiumAr,
      PHOTO.genS,
      COLOR.gray,
      POL.none,
      TINT.none,
      MIRROR.none,
      1,
      "off_sv_poly_gens_mw",
    ),
    rule(
      organizationId,
      "rr_pg_xtr_1",
      "PG XTRActive Brown — preferred",
      PROD.pgClear,
      MAT.hi167,
      COAT.premiumAr,
      PHOTO.xtractive,
      COLOR.brown,
      POL.none,
      TINT.none,
      MIRROR.none,
      1,
      "off_pg_167_xtr_br_mw",
    ),
    rule(
      organizationId,
      "rr_sv_pol_1",
      "SV Polar Gray — preferred",
      PROD.svSun,
      MAT.poly,
      COAT.backsideAr,
      null,
      null,
      POL.gray,
      TINT.none,
      MIRROR.none,
      1,
      "off_sv_poly_pol_ss",
    ),
    rule(
      organizationId,
      "rr_pg_pol_1",
      "PG Polar Brown — preferred",
      PROD.pgSun,
      MAT.hi167,
      COAT.premiumAr,
      null,
      null,
      POL.brown,
      TINT.none,
      MIRROR.none,
      1,
      "off_pg_pol_br_ss",
    ),
    rule(
      organizationId,
      "rr_xtrpol_1",
      "SV XTRActive Polarized — preferred",
      PROD.svClear,
      MAT.poly,
      COAT.premiumAr,
      PHOTO.xtractivePol,
      COLOR.gray,
      POL.none,
      TINT.none,
      MIRROR.none,
      1,
      "off_sv_xtrpol_mw",
    ),
    rule(
      organizationId,
      "rr_fl41_1",
      "SV FL-41 — preferred",
      PROD.svClear,
      MAT.poly,
      COAT.hard,
      null,
      null,
      POL.none,
      TINT.fl41,
      MIRROR.none,
      1,
      "off_sv_fl41_ss",
    ),
    rule(
      organizationId,
      "rr_mirror_1",
      "SV Polar Mirror — preferred",
      PROD.svSun,
      MAT.poly,
      COAT.backsideAr,
      null,
      null,
      POL.gray,
      TINT.none,
      MIRROR.blue,
      1,
      "off_sv_mirror_ss",
    ),
  ];

  return {
    ...emptyDatabase(),
    ...reference,
    products,
    productMaterials,
    labs,
    locations: [
      { id: LOC_MAIN, organizationId, name: "Main", active: true },
      { id: LOC_NORTH, organizationId, name: "North", active: true },
    ],
    offerings,
    routingRules,
  };
}

function rule(
  organizationId: string,
  id: string,
  name: string,
  lensProductId: string,
  lensMaterialId: string,
  coatingId: string | null,
  photochromicProductId: string | null,
  photochromicColorId: string | null,
  polarizationOptionId: string | null,
  tintOptionId: string | null,
  mirrorOptionId: string | null,
  priority: number,
  labLensOfferingId: string,
  locationId: string | null = null,
): RoutingRule {
  const productVision =
    lensProductId === PROD.pgClear || lensProductId === PROD.pgSun ? VT.pg : VT.sv;
  const productDesign =
    lensProductId === PROD.pgClear || lensProductId === PROD.pgSun
      ? LD.ffPg
      : lensProductId === PROD.svSun
        ? LD.asphericSv
        : LD.convSv;
  return {
    id,
    organizationId,
    locationId,
    name,
    visionTypeId: productVision,
    lensDesignId: productDesign,
    lensProductId,
    lensMaterialId,
    coatingId,
    photochromicProductId,
    photochromicColorId,
    polarizationOptionId,
    tintOptionId,
    mirrorOptionId,
    insurancePlanId: null,
    priority,
    labLensOfferingId,
    active: true,
    effectiveStartDate: "2026-01-01",
    effectiveEndDate: null,
    notes: "",
    createdBy: DEMO_USER_ID,
    ...stamp,
  };
}
